version: '3.2'
services:
  sqlserver:
    image: microsoft/mssql-server-linux
    environment:
      - 'ACCEPT_EULA=Y'
      - 'SA_PASSWORD=passWORD1234'
    ports:
      - '1433:1433'
  python:
    build: .
    links:
      - sqlserver
    command:
      - nosetests
    volumes:
      - ./tests/:/tests

volumes:
  tests: {}
