version: '3.2'
services:
  sqlserver:
    image: microsoft/mssql-server-linux:latest@sha256:19b9392f035fc9f82b77f6833d1490bca8cb041b445cd451de0d1f1f3efe70e8
    environment:
      - 'ACCEPT_EULA=Y'
      - 'SA_PASSWORD=passWORD1234'
    ports:
      - '1433:1433'
  python:
    build: .
    links:
      - sqlserver
    command:
      - nosetests
    volumes:
      - ./tests/:/tests

volumes:
  tests: {}
