version: '3.2'
services:
  sqlserver:
    image: microsoft/mssql-server-linux:latest@sha256:4f769a0b6603f9de2496e3ee455ce6b8b44db642714b50ed89b033e03e6e1e91
    environment:
      - 'ACCEPT_EULA=Y'
      - 'SA_PASSWORD=passWORD1234'
    ports:
      - '1433:1433'
  python:
    build: .
    links:
      - sqlserver
    command:
      - nosetests
    volumes:
      - ./tests/:/tests

volumes:
  tests: {}
