version: 2
jobs:
  build:
    machine:
      docker_layer_caching: false

    steps:
      - checkout

      - run:
          name: build image
          command: |
            docker-compose build python

      - run:
          name: run tests
          command: |
            docker-compose run --rm python
