version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - restore_cache:
          keys:
          - docker-cache

      - run:
          name: build image
          command: |
            docker-compose build python

      - run:
          name: run tests
          command: |
            docker-compose run --rm python

      - save_cache:
          paths:
            - /var/lib/docker
          key: docker-cache
